netstores/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.flatpages.views import flatpage
from django.views.decorators.cache import cache_page
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView
from django.views.i18n import javascript_catalog, set_language

urlpatterns = [
    url(r'^$', cache_page(15*60)(TemplateView.as_view(template_name='base.html')), name='main_page'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'persons/', include('person.urls')),
    url(r'stores/', include('store.urls')),
    url(r'places/', include('place.urls')),
    url(r'storages/', include('storage.urls')),

    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', javascript_catalog, name='jsi18n'),
    url(r'^jsi18n/set_lang/$', csrf_exempt(set_language), name='set_language'),

    url(r'^pages(?P<url>.*)$', flatpage, name='flatpage')
]

place/urls.py
from django.conf.urls import url
from place.views import CountriesListView, CitiesListView, CountryDetailView, CityDetailView, CountryUpdateView, \
    CityUpdateView, CountryCreateView, CityCreateView, CityDelete, CountryDelete

urlpatterns = [
    url(r'^countries/$', CountriesListView.as_view(), name='countries'),
    url(r'^country/(?P<pk>\d+)/$', CountryDetailView.as_view(), name='country'),
    url(r'^cities/$', CitiesListView.as_view(), name='cities'),
    url(r'^city/(?P<pk>\d+)/$', CityDetailView.as_view(), name='city'),
    url(r'^country/edit/(?P<pk>\d+)/$', CountryUpdateView.as_view(), name='country_edit'),
    url(r'^city/edit/(?P<pk>\d+)/$', CityUpdateView.as_view(), name='city_edit'),
    url(r'^country/edit/(?P<pk>new)/$', CountryCreateView.as_view(), name='country_create'),
    url(r'^city/edit/(?P<pk>new)/$', CityCreateView.as_view(), name='city_create'),
    url(r'^city/delete/(?P<pk>\d+)/$', CityDelete.as_view(), name='city_delete'),
    url(r'^country/delete/(?P<pk>\d+)/$', CountryDelete.as_view(), name='country_delete'),
]

store/urls.py
from django.conf.urls import url
from store.views import StoresListView, StoreDetailView, TypesListView, TypeDetailView, StoreEditView, TypeEditView, \
    StoreDelete, TypeDelete

urlpatterns = [
    url(r'^stores/$', StoresListView.as_view(), name='stores'),
    url(r'^types/$', TypesListView.as_view(), name='types'),
    url(r'^store/(?P<pk>\d+)/$', StoreDetailView.as_view(), name='store'),
    url(r'^store/edit/(?P<pk>\d+|new)/$', StoreEditView.as_view(), name='store_edit'),
    url(r'^type/(?P<pk>\d+)/$', TypeDetailView.as_view(), name='type'),
    url(r'^type/edit/(?P<pk>\d+|new)/$', TypeEditView.as_view(), name='type_edit'),
    url(r'^store/delete/(?P<pk>\d+)/$', StoreDelete.as_view(), name='store_delete'),
    url(r'^type/delete/(?P<pk>\d+)/$', TypeDelete.as_view(), name='type_delete'),
]

store/models.py
from django.db import models
from django.db.models import F
from django.db.models.signals import post_save
from django.dispatch import receiver

from person.models import Person
from place.models import City
from storage.models import Storage


class TypeOfStore(models.Model):
    name = models.CharField(max_length=100)

    def __unicode__(self):
        return u'{}'.format(self.name)


class Store(models.Model):
    type = models.ForeignKey(TypeOfStore)
    name = models.CharField(max_length=80)
    owner = models.ForeignKey(Person, related_name='own_store')
    sellers = models.ManyToManyField(Person, related_name='seller_in')
    storage = models.ManyToManyField(Storage)
    city = models.ForeignKey(City)
    address = models.CharField(max_length=250)
    site = models.URLField(blank=True, null=True)
    v = models.PositiveIntegerField(default=0, editable=False)

    def __unicode__(self):
        return u'{} ({})'.format(self.name, self.type)


@receiver(post_save, sender=Store)
def inc_store_version(sender, instance, **kwargs):
    Store.objects.filter(pk=instance.pk).update(v=F('v') + 1)

store/forms.py
from django import forms
from netstores.forms import BootstrapFormMixin
from store.models import Store, TypeOfStore


class StoreEditForm(forms.ModelForm, BootstrapFormMixin):
    class Meta:
        model = Store
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(StoreEditForm, self).__init__(*args, **kwargs)
        BootstrapFormMixin.__init__(self)


class TypeEditForm(forms.ModelForm, BootstrapFormMixin):
    class Meta:
        model = TypeOfStore
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(TypeEditForm, self).__init__(*args, **kwargs)
        BootstrapFormMixin.__init__(self)

store/views.py
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView, TemplateView, DeleteView
from store.forms import StoreEditForm, TypeEditForm
from store.models import Store, TypeOfStore


class StoresListView(ListView):
    model = Store


class TypesListView(ListView):
    model = TypeOfStore


class StoreDetailView(DetailView):
    model = Store

    def get_context_data(self, **kwargs):
            context = super(StoreDetailView, self).get_context_data(**kwargs)
            store = super(StoreDetailView, self).get_object()
            context['sellers'] = store.sellers.all()
            context['storages'] = store.storage.all()
            return context


class TypeDetailView(DetailView):
    model = TypeOfStore


class StoreEditView(TemplateView):
    template_name = 'store/store_edit.html'

    @method_decorator(permission_required('store.change_store', raise_exception=True))
    def dispatch(self, request, *args, **kwargs):
        if kwargs['pk'] != 'new':
            self.instance = get_object_or_404(Store, pk=kwargs['pk'])
        else:
            self.instance = None
        self.form = StoreEditForm(request.POST or None, instance=self.instance)
        return super(StoreEditView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(StoreEditView, self).get_context_data(**kwargs)
        context['form'] = self.form
        return context

    def post(self, request, *args, **kwargs):
        if self.form.is_valid():
            saved_instance = self.form.save()
            if not self.instance:
                messages.success(request, u'The store created successfully')
            else:
                messages.success(request, u'The store saved successfully')
            return redirect('store', pk=saved_instance.pk)
        return self.get(request, *args, **kwargs)


class TypeEditView(TemplateView):
    template_name = 'store/type_edit.html'

    @method_decorator(permission_required('typeofstore.change_typeofstore', raise_exception=True))
    def dispatch(self, request, *args, **kwargs):
        if kwargs['pk'] != 'new':
            self.instance = get_object_or_404(TypeOfStore, pk=kwargs['pk'])
        else:
            self.instance = None
        self.form = TypeEditForm(request.POST or None, instance=self.instance)
        return super(TypeEditView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(TypeEditView, self).get_context_data(**kwargs)
        context['form'] = self.form
        return context

    def post(self, request, *args, **kwargs):
        if self.form.is_valid():
            saved_instance = self.form.save()
            if not self.instance:
                messages.success(request, u'Type created successfully')
            else:
                messages.success(request, u'Type saved successfully')
            return redirect('type', pk=saved_instance.pk)
        return self.get(request, *args, **kwargs)


class StoreDelete(DeleteView):
    model = Store
    success_url = reverse_lazy('stores')

    @method_decorator(permission_required('store.delete_store', raise_exception=True))
    def dispatch(self, request, *args, **kwargs):
        return super(StoreDelete, self).dispatch(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        response = super(StoreDelete, self).delete(request, *args, **kwargs)
        messages.success(request, u'Store deleted successfully')
        return response


class TypeDelete(DeleteView):
    model = TypeOfStore
    success_url = reverse_lazy('types')

    @method_decorator(permission_required('typeofstore.delete_typeofstore', raise_exception=True))
    def dispatch(self, request, *args, **kwargs):
        return super(TypeDelete, self).dispatch(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        response = super(TypeDelete, self).delete(request, *args, **kwargs)
        messages.success(request, u'Type of store deleted successfully')
        return response

store/templates/store/store_confirm_delete.html
{% extends 'base.html' %}


{% block content %}
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm" class="btn btn-danger"/>
    </form>
{% endblock %}

store/templates/store/store_detail.html
{% extends 'base.html' %}
{% load netstores %}

{% block content %}
    <p><span class="text-muted">Name:</span> {{ object.name }}</p>
    <p><span class="text-muted">Type:</span> <a href="{% url 'type' object.type.pk %}">{{ object.type }}</a></p>
    <p><span class="text-muted">Owner:</span> <a href="{% url 'person' object.owner.pk %}">{{ object.owner }}</a></p>
    <p><span class="text-muted">Sellers:</span>
        {% for sale in object|sales_list %}
            <a href="{% url 'person' sale.pk %}">{{ sale }}</a>
        {% endfor %}
    </p>
    <p><span class="text-muted">Storages:</span>
        {% for storage in storages %}
            <a href="{% url 'storage' storage.pk %}">{{ storage }}</a>
        {% endfor %}
    </p>
    <p><span class="text-muted">City:</span> <a href="{% url 'city' object.city.pk %}">{{ object.city }}</a></p>
    <p><span class="text-muted">Address:</span> {{ object.address }}</p>
    {% if object.site %}
        <p><span class="text-muted">Site: </span><a href="{{ object.site }}" target="_blank">{{ object.site }}</a></p>
    {% endif %}
    <p><span class="text-muted">Version:</span> {{ object.v }}</p>
    {% if perms.store.change_store %}
        <p><a href="{% url 'store_edit' object.pk %}" class="btn btn-default">Edit</a></p>
    {% endif %}
    {% if perms.store.delete_store %}
        <p><a href="{% url 'store_delete' object.pk %}" class="btn btn-danger">Delete</a></p>
    {% endif %}
{% endblock %}

store/templates/store/store_edit.html
{% extends 'base.html' %}
{% load netstores %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {% for field in form %}
            {% show_form_field_errors field.errors %}
            <div class="row" style="margin-bottom: 15px">
                <div class="form-group{% if field.errors %} has-error{% endif %}">
                    <label for="{{ field.id_for_label }}" class="col-md-1 control-label">{{ field.label }}</label>
                    <div class="col-md-4">
                        {{ field }}
                    </div>
                </div>
            </div>
        {% endfor %}
        <div class="form-group">
            <div class="col-md-4">
                <input type="submit" class="btn btn-success" value="Save">
                <a href="{% url 'stores' %}" class="btn btn-default">Back to Stores</a>
                {% if form.instance.pk and perms.store.delete_store %}
                    <a href="{% url 'store_delete' form.instance.pk %}" class="btn btn-danger pull-right">
                        Delete
                    </a>
                {% endif %}
            </div>
        </div>
    </form>
{% endblock %}

store/templates/store/store_list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Stores</h1>
    {% if perms.store.add_store %}
        <a href="{% url 'store_edit' 'new' %}" class="btn btn-lg btn-success" style="margin-bottom: 15px">Add</a>
    {% endif %}
    <table class="table table-hover">
        {% for store in object_list %}
            <tr>
                <td><a href="{% url 'store' store.pk %}">{{ store.name }}</a></td>
                {% if perms.store.change_store %}
                    <td><a href="{% url 'store_edit' store.pk %}">
                        <span class="glyphicon glyphicon-pencil"></span> Edit</a></td>
                {% endif %}
            </tr>
        {% endfor %}
    </table>
{% endblock %}

store/templates/store/type_edit.html
{% extends 'base.html' %}
{% load netstores %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {% for field in form %}
            {% show_form_field_errors field.errors %}
            <div class="row" style="margin-bottom: 15px">
                <div class="form-group{% if field.errors %} has-error{% endif %}">
                    <label for="{{ field.id_for_label }}" class="col-md-1 control-label">{{ field.label }}</label>
                    <div class="col-md-4">
                        {{ field }}
                    </div>
                </div>
            </div>
        {% endfor %}
        <div class="form-group">
            <div class="col-md-4">
                <input type="submit" class="btn btn-success" value="Save">
                <a href="{% url 'types' %}" class="btn btn-default">Back to Types</a>
                {% if form.instance.pk and perms.typeofstore.delete_typeofstore %}
                    <a href="{% url 'type_delete' form.instance.pk %}" class="btn btn-danger pull-right">
                        Delete
                    </a>
                {% endif %}
            </div>
        </div>
    </form>
{% endblock %}

store/templates/store/typeofstore_confirm_delete.html
{% extends 'base.html' %}


{% block content %}
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm" class="btn btn-danger"/>
    </form>
{% endblock %}

store/templates/store/typeofstore_detail.html
{% extends 'base.html' %}

{% block content %}
    <p>{{ object.name }}</p>
    <p><a href="{% url 'type_edit' object.pk %}" class="btn btn-default">Edit</a></p>
    <p><a href="{% url 'type_delete' object.pk %}" class="btn btn-danger">Delete</a></p>
{% endblock %}

store/templates/store/typeofstore_list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Types</h1>
    {% if perms.typeofstore.add_typeofstore %}
        <a href="{% url 'type_edit' 'new' %}" class="btn btn-lg btn-success" style="margin-bottom: 15px">Add</a>
    {% endif %}
    <table class="table table-hover">
        {% for type in object_list %}
            <tr>
                <td><a href="{% url 'type' type.pk %}">{{ type.name }}</a></td>
                {% if perms.typeofstore.change_typeofstore %}
                    <td><a href="{% url 'type_edit' type.pk %}">
                        <span class="glyphicon glyphicon-pencil"></span> Edit</a></td>
                {% endif %}
            </tr>
        {% endfor %}
    </table>
{% endblock %}